### ISSUE TITLE
Repository error display in Log file associated with Pentaho Dashboards

### ISSUE THREAD

**Issue by jwmccartha** [seibelsbi/sbi#12]
Dashboards created by hards some time ago, are not displaying any data when he opens them. This problem started yesterday, Aug 24, 2015 in BI02. A DW team member looked into this more and realized an error displayed in the Log file. The error is Repository can't be found.

Attached is the error:
![image](https://cloud.githubusercontent.com/assets/13457493/9480254/245afe3c-4b50-11e5-9996-3a75e79f12e9.png)

**Comment by ManuelCalavera** [comment]
As we've changed environment I'm closing this one to be reopened if the issue reappears.
