### ISSUE TITLE
Add new Agency fields to Pentaho's Claims cubes

### ISSUE THREAD

**Issue by jwmccartha** [seibelsbi/sbi#27]
The below list of Agency fields need to be added to the Claims cubes:

Agency Name
Agency Name 2
Agency Address 1
Agency Address 2

**Comment by ManuelCalavera** [comment]
Added and PR issued to @rxacevedo . Data there, only missing on cube.

**Comment by jwmccartha** [comment]
@rxacevedo @ManuelCalavera I am signing off on the Agency dimension test in the Claim Snapshot and Claim Transaction cubes. I am in agreement with the PR closing #47 and SBI#27 issues.
