### ISSUE TITLE
Make additional Agency fields available in Pentaho

### ISSUE THREAD

**Issue by jwmccartha** [seibelsbi/sbi#31]
The below list of fields should be added to Pentaho.

Fields exist in DimAgency table:
Appointed Date
Transfer Reason
Transfer Date
Do Not Renew Indicator
Binding Authority Indicator 

Ref: seibelsbi/pba-models/issues/55

**Comment by mb56142** [comment]
@marchise @rxacevedo : Mentioned fields already exists in analytical database. Please add those Agency fields on metadata model/cube/OLAP. Thanks

**Comment by ManuelCalavera** [comment]
Work done. All fields have been added as properties. Closing.
